brew 'dash'
brew 'fish'
brew 'the_silver_searcher'

cask 'flycut'
cask 'gitx'
cask 'iterm2'
cask 'orbstack'
cask 'proton-pass'
cask 'protonvpn'
cask 'slack'
cask 'ungoogled-chromium'
cask 'usb-overdrive'
cask 'visual-studio-code'
cask 'waterfox'
