#!/usr/bin/env bash

sudo -v

brew bundle --file=~/src/dotfiles/Brewfile

ln -sf ~/src/dotfiles/.gitconfig ~/.gitconfig
ln -sf ~/src/dotfiles/.gitignore ~/.gitignore
mkdir ~/.config/fish
ln -sf ~/src/dotfiles/config.fish ~/.config/fish/config.fish
ln -sf ~/src/dotfiles/vscode-settings.json ~/Library/Application\ Support/Code/User/settings.json
sudo ln -f ~/src/dotfiles/hosts /etc/hosts

if [[ $(dscl . -read /Users/`id -un`/ UserShell) =~ .*fish$ ]];
then
  echo "Shell already set to fish"
else
  echo `which fish` | sudo tee -a /etc/shells
  chsh -s `which fish`
fi
